global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: ""
rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "solr"
    static_configs:
      - targets:
          - "solr_node1:9854"
  - job_name: "docker-container"
    static_configs:
      - targets:
          - "docker-exporter:8080"
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "node-exporter:9100"
