{
 "title": "Sisense Cluster Detail Dashboard",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(machine_cpu_cores, node)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(machine_cpu_cores,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$Node\",service=~\"^$Service$\"}[1m])) / sum (machine_cpu_cores{node=~\"$Node\",service=~\"^$Service$\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\",service=~\"^$Service$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"$Node\",service=~\"^$Service$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\",service=~\"^$Service$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"})"
    }
   ]
  },
  {
   "title": "CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",service=~\"^$Service$\"}[1m])) / sum (machine_cpu_cores{service=~\"^$Service$\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}[1m])) by (node) / sum (machine_cpu_cores{node=~\"^$Node$\",service=~\"^$Service$\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",service=~\"^$Service$\"}) / sum (machine_memory_bytes{service=~\"^$Service$\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (node) / sum (machine_memory_bytes{node=~\"^$Node$\",service=~\"^$Service$\"}) by (node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (pod)",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "count(mixin_pod_workload{namespace=\"sisense\"}) by (workload)"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"sisense\", container!=\"\",node=~\"$Node\",service=~\"$Service\"}\n  * on(namespace,pod)\n    group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"sisense\",node=~\"$Node\"}\n* on(namespace,pod)\n  group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"sisense\", container!=\"\", node=~\"$Node\",service=~\"$Service\"}\n  * on(namespace,pod)\n    group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"sisense\",node=~\"$Node\"}\n* on(namespace,pod)\n  group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods CPU usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "count(mixin_pod_workload{namespace=\"sisense\"}) by (workload)"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{node=~\"$Node\",service=~\"$Service\",namespace=\"sisense\"}[1m])\n* on(namespace,pod)\n  group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"sisense\",node=~\"$Node\"}\n* on(namespace,pod)\n  group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n"
    },
    {
     "expr": "sum(\n  rate (container_cpu_usage_seconds_total{node=~\"$Node\",service=~\"^$Service$\",namespace=\"sisense\"}[1m])\n* on(namespace,pod)\n  group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"sisense\",node=~\"$Node\"}\n* on(namespace,pod)\n  group_left(workload) mixin_pod_workload{namespace=\"sisense\"}\n) by (workload)\n"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\".*\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Numbers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_info{node=~\"$Node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\", node=~\"$Node\", status!=\"true\"})",
       "legendFormat": "Unavailable"
      }
     ]
    },
    {
     "title": "Disk Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$Node\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Memory Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\"$Node\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "PID Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", node=~\"$Node\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Unschedulable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{node=~\"$Node\"})"
      }
     ]
    },
    {
     "title": "Out of Disk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$Node\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Network Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", node=~\"$Node\", status!=\"false\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\".*\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\".*\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\".*\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\".*\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts{namespace=~\".*\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\".*\", node=~\"$Node\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\",service=~\"^$Service$\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\",service=~\"^$Service$\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System services CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (node, name, image)",
       "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (node, rkt_container_name)",
       "legendFormat": "rkt: {{ node }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All processes CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (node, name, image)",
       "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (node, rkt_container_name)",
       "legendFormat": "rkt: {{ node }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (node, name, image)",
       "legendFormat": "-> docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (node, name, image)",
       "legendFormat": "<- docker: {{ node }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (node, rkt_container_name)",
       "legendFormat": "-> rkt: {{ node }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (node, rkt_container_name)",
       "legendFormat": "<- rkt: {{ node }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",node=~\"^$Node$\",service=~\"^$Service$\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}